basePath: /
definitions:
  model.Pet:
    properties:
      age:
        type: integer
      birthday:
        type: string
      breed_id:
        type: integer
      color:
        type: string
      creation_date:
        type: string
      food:
        type: string
      gender:
        type: string
      id:
        type: integer
      lives_at:
        type: string
      lost:
        type: boolean
      name:
        type: string
      photo:
        type: string
      spicies:
        type: string
      status:
        type: string
      weight:
        type: number
    type: object
  model.PetCreateRequest:
    properties:
      age:
        type: integer
      birthday:
        type: string
      color:
        type: string
      food:
        type: string
      gender:
        type: string
      lives_at:
        type: string
      name:
        type: string
      spicies:
        type: string
      weight:
        type: number
    type: object
  model.PetUpdateRequest:
    properties:
      age:
        type: integer
      birthday:
        type: string
      color:
        type: string
      food:
        type: string
      gender:
        type: string
      lives_at:
        type: string
      lost:
        type: boolean
      name:
        type: string
      spicies:
        type: string
      weight:
        type: number
    type: object
  model.RemoveImageResponse:
    properties:
      message:
        type: string
    type: object
  model.UploadImageResponse:
    properties:
      imageURL:
        type: string
      message:
        type: string
    type: object
  model.User:
    properties:
      email:
        type: string
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
      password:
        type: string
      phone_number:
        type: string
      repeat_password:
        type: string
    type: object
  model.UserLoginRequest:
    properties:
      password:
        type: string
      phone_number:
        type: string
    type: object
  model.UserUpdateRequest:
    properties:
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
      phone_number:
        type: string
      repeat_password:
        type: string
    type: object
host: http://localhost:8080
info:
  contact: {}
  description: API server for Native HappyPets application
  title: HappyPets RestAPI
  version: "1.0"
paths:
  /api/pet/:
    get:
      consumes:
      - application/json
      description: Возвращает список всех питомцев пользователя.
      produces:
      - application/json
      responses:
        "200":
          description: Список питомцев пользователя
          schema:
            items:
              $ref: '#/definitions/model.Pet'
            type: array
        "500":
          description: Внутренняя ошибка сервера
          schema:
            items:
              $ref: '#/definitions/model.Pet'
            type: array
      security:
      - ApiKeyAuth: []
      summary: Получение списка всех питомцев пользователя.
      tags:
      - Питомец
  /api/pet/{petID}:
    get:
      consumes:
      - application/json
      description: Возвращает информацию о питомце по его ID.
      parameters:
      - description: ID питомца
        in: path
        name: petID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Информация о питомце
          schema:
            $ref: '#/definitions/model.Pet'
        "400":
          description: Неверный запрос
          schema:
            $ref: '#/definitions/model.Pet'
        "404":
          description: Питомец не найден
          schema:
            $ref: '#/definitions/model.Pet'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/model.Pet'
      security:
      - ApiKeyAuth: []
      summary: Получение информации о питомце по его ID.
      tags:
      - Питомец
  /api/pet/create:
    post:
      consumes:
      - application/json
      description: Создайте нового питомца с предоставленной информацией.
      parameters:
      - description: Объект PetCreateRequest в формате JSON
        in: body
        name: pet
        required: true
        schema:
          $ref: '#/definitions/model.PetCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Питомец успешно создан
          schema:
            $ref: '#/definitions/model.Pet'
      security:
      - ApiKeyAuth: []
      summary: Создание нового питомца.
      tags:
      - Питомец
  /api/pet/delete/{petID}:
    delete:
      consumes:
      - application/json
      description: Удаляет питомца по заданному идентификатору.
      parameters:
      - description: ID питомца
        in: path
        name: petID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: Питомец успешно удален
        "400":
          description: Неверный запрос
        "404":
          description: Питомец не найден
      security:
      - ApiKeyAuth: []
      summary: Удаление питомца.
      tags:
      - Питомец
  /api/pet/image/remove/{petID}:
    delete:
      consumes:
      - application/json
      description: Удаляет изображение из Minio happypets-image(bucket) определенного
        домашнего животного, связанного с пользователем.
      parameters:
      - description: Pet ID
        in: path
        name: petID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Изображение успешно удалено
          schema:
            $ref: '#/definitions/model.RemoveImageResponse'
        "400":
          description: Неверный запрос, неверные входные данные
          schema:
            $ref: '#/definitions/model.RemoveImageResponse'
        "404":
          description: Изображение не найдено
          schema:
            $ref: '#/definitions/model.RemoveImageResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/model.RemoveImageResponse'
      security:
      - ApiKeyAuth: []
      summary: Удаляет изображение из Minio happypets-image(bucket) определенного
        домашнего животного, связанного с пользователем.
      tags:
      - Питомец
  /api/pet/image/upload/{petID}:
    post:
      consumes:
      - multipart/form-data
      description: Загружает изображение в Minio happypets-image(bucket) определенного
        домашнего животного, связанного с пользователем.
      parameters:
      - description: Pet ID
        in: path
        name: petID
        required: true
        type: string
      - description: Image file
        in: formData
        name: image
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Изображение успешно загружено
          schema:
            $ref: '#/definitions/model.UploadImageResponse'
        "400":
          description: Неверный запрос, неверные входные данные
          schema:
            $ref: '#/definitions/model.UploadImageResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/model.UploadImageResponse'
      security:
      - ApiKeyAuth: []
      summary: Загружает изображение в Minio happypets-image(bucket) определенного
        домашнего животного, связанного с пользователем.
      tags:
      - Питомец
  /api/pet/update/{petID}:
    put:
      consumes:
      - application/json
      description: Обновляет информацию о питомце с предоставленными данными.
      parameters:
      - description: ID питомца
        in: path
        name: id
        required: true
        type: integer
      - description: Объект PetUpdateRequest в формате JSON
        in: body
        name: pet
        required: true
        schema:
          $ref: '#/definitions/model.PetUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Питомец успешно обновлен
          schema:
            $ref: '#/definitions/model.Pet'
        "400":
          description: Неверный запрос
          schema:
            $ref: '#/definitions/model.Pet'
      security:
      - ApiKeyAuth: []
      summary: Обновление информации о питомце.
      tags:
      - Питомец
  /user/login:
    post:
      consumes:
      - application/json
      description: Авторизация пользователя и генерация JWT-токена
      parameters:
      - description: Данные для входа
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.UserLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Успешный ответ
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Неверный запрос
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Внутренняя ошибка сервера
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Вход пользователя
      tags:
      - Пользователь
  /user/register:
    post:
      consumes:
      - application/json
      description: Регистрация нового пользователя с предоставленной информацией.
      parameters:
      - description: Пользовательский объект в формате JSON
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "201":
          description: Успешно зарегистрированный пользователь
          schema:
            $ref: '#/definitions/model.User'
      summary: Регистрация нового пользователя.
      tags:
      - Пользователь
  /users/{userID}:
    get:
      description: Получение данных пользователя по его идентификатору
      parameters:
      - description: Идентификатор пользователя
        in: path
        name: userID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Успешный ответ
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Неверный запрос
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Внутренняя ошибка сервера
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получить пользователя по идентификатору
    put:
      consumes:
      - application/json
      description: Обновление данных пользователя по его идентификатору
      parameters:
      - description: Идентификатор пользователя
        in: path
        name: userID
        required: true
        type: integer
      - description: Данные для обновления
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.UserUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Успешный ответ
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Неверный запрос
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Внутренняя ошибка сервера
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Обновить данные пользователя
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
