definitions:
  model.RemoveImageResponse:
    properties:
      message:
        type: string
    type: object
  model.UploadImageResponse:
    properties:
      imageURL:
        type: string
      message:
        type: string
    type: object
  model.User:
    properties:
      email:
        type: string
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
      password:
        type: string
      repeat_password:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/image/remove/{userID}/{petID}:
    delete:
      consumes:
      - application/json
      description: Удаляет изображение из Minio happypets-image(bucket) определенного
        домашнего животного, связанного с пользователем.
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: string
      - description: Pet ID
        in: path
        name: petID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Изображение успешно удалено
          schema:
            $ref: '#/definitions/model.RemoveImageResponse'
        "400":
          description: Неверный запрос, неверные входные данные
          schema:
            $ref: '#/definitions/model.RemoveImageResponse'
        "404":
          description: Изображение не найдено
          schema:
            $ref: '#/definitions/model.RemoveImageResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/model.RemoveImageResponse'
      summary: Удаляет изображение из Minio happypets-image(bucket) определенного
        домашнего животного, связанного с пользователем.
      tags:
      - Изображение
  /api/image/upload/{userID}/{petID}:
    post:
      consumes:
      - multipart/form-data
      description: Загружает изображение в Minio happypets-image(bucket) определенного
        домашнего животного, связанного с пользователем.
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: string
      - description: Pet ID
        in: path
        name: petID
        required: true
        type: string
      - description: Image file
        in: formData
        name: image
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Изображение успешно загружено
          schema:
            $ref: '#/definitions/model.UploadImageResponse'
        "400":
          description: Неверный запрос, неверные входные данные
          schema:
            $ref: '#/definitions/model.UploadImageResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/model.UploadImageResponse'
      summary: Загружает изображение в Minio happypets-image(bucket) определенного
        домашнего животного, связанного с пользователем.
      tags:
      - Изображение
  /api/user/register:
    post:
      consumes:
      - application/json
      description: Регистрация нового пользователя с предоставленной информацией.
      parameters:
      - description: Пользовательский объект в формате JSON
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "201":
          description: Успешно зарегистрированный пользователь
          schema:
            $ref: '#/definitions/model.User'
      summary: Регистрация нового пользователя.
      tags:
      - Пользователь
swagger: "2.0"
