definitions:
  model.Pet:
    properties:
      birthdate:
        type: string
      breed_id:
        type: integer
      color:
        type: string
      created_at:
        type: string
      description:
        type: string
      food:
        type: string
      gender:
        type: string
      id:
        type: integer
      lives_at:
        type: string
      name:
        type: string
      passport_id:
        type: integer
      photos:
        items:
          type: string
        type: array
      spicies:
        type: string
      status:
        type: string
      todo_id:
        type: integer
      weight:
        type: number
    type: object
  model.PetUpdateRequest:
    properties:
      birthdate:
        type: string
      color:
        type: string
      description:
        type: string
      food:
        type: string
      gender:
        type: string
      id:
        type: integer
      name:
        type: string
      photos:
        items:
          type: string
        type: array
      spicies:
        type: string
      weight:
        type: number
    type: object
  model.RemoveImageResponse:
    properties:
      message:
        type: string
    type: object
  model.UploadImageResponse:
    properties:
      imageURL:
        type: string
      message:
        type: string
    type: object
  model.User:
    properties:
      email:
        type: string
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
      password:
        type: string
      repeat_password:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/pet/create:
    post:
      consumes:
      - application/json
      description: Создайте нового питомца с предоставленной информацией.
      parameters:
      - description: Объект Pet в формате JSON
        in: body
        name: pet
        required: true
        schema:
          $ref: '#/definitions/model.Pet'
      produces:
      - application/json
      responses:
        "201":
          description: Питомец успешно создан
          schema:
            $ref: '#/definitions/model.Pet'
      summary: Создание нового питомца.
      tags:
      - Питомец
  /api/pet/image/remove/{userID}/{petID}:
    delete:
      consumes:
      - application/json
      description: Удаляет изображение из Minio happypets-image(bucket) определенного
        домашнего животного, связанного с пользователем.
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: string
      - description: Pet ID
        in: path
        name: petID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Изображение успешно удалено
          schema:
            $ref: '#/definitions/model.RemoveImageResponse'
        "400":
          description: Неверный запрос, неверные входные данные
          schema:
            $ref: '#/definitions/model.RemoveImageResponse'
        "404":
          description: Изображение не найдено
          schema:
            $ref: '#/definitions/model.RemoveImageResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/model.RemoveImageResponse'
      summary: Удаляет изображение из Minio happypets-image(bucket) определенного
        домашнего животного, связанного с пользователем.
      tags:
      - Изображение
  /api/pet/image/upload/{userID}/{petID}:
    post:
      consumes:
      - multipart/form-data
      description: Загружает изображение в Minio happypets-image(bucket) определенного
        домашнего животного, связанного с пользователем.
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: string
      - description: Pet ID
        in: path
        name: petID
        required: true
        type: string
      - description: Image file
        in: formData
        name: image
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Изображение успешно загружено
          schema:
            $ref: '#/definitions/model.UploadImageResponse'
        "400":
          description: Неверный запрос, неверные входные данные
          schema:
            $ref: '#/definitions/model.UploadImageResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/model.UploadImageResponse'
      summary: Загружает изображение в Minio happypets-image(bucket) определенного
        домашнего животного, связанного с пользователем.
      tags:
      - Изображение
  /api/pet/update/{id}:
    put:
      consumes:
      - application/json
      description: Обновляет информацию о питомце с предоставленными данными.
      parameters:
      - description: ID питомца
        in: path
        name: id
        required: true
        type: integer
      - description: Объект PetUpdateRequest в формате JSON
        in: body
        name: pet
        required: true
        schema:
          $ref: '#/definitions/model.PetUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Питомец успешно обновлен
          schema:
            $ref: '#/definitions/model.PetUpdateRequest'
        "400":
          description: Неверный запрос
          schema:
            $ref: '#/definitions/model.PetUpdateRequest'
      summary: Обновление информации о питомце.
      tags:
      - Питомец
  /api/pet/update/{id}:
    put:
      consumes:
      - application/json
      description: Обновляет информацию о питомце с предоставленными данными.
      parameters:
      - description: ID питомца
        in: path
        name: id
        required: true
        type: integer
      - description: Объект Pet в формате JSON
        in: body
        name: pet
        required: true
        schema:
          $ref: '#/definitions/model.Pet'
      produces:
      - application/json
      responses:
        "200":
          description: Питомец успешно обновлен
          schema:
            $ref: '#/definitions/model.Pet'
        "400":
          description: Неверный запрос
          schema:
            $ref: '#/definitions/model.Pet'
      summary: Обновление информации о питомце.
      tags:
      - Питомец
  /api/user/register:
    post:
      consumes:
      - application/json
      description: Регистрация нового пользователя с предоставленной информацией.
      parameters:
      - description: Пользовательский объект в формате JSON
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "201":
          description: Успешно зарегистрированный пользователь
          schema:
            $ref: '#/definitions/model.User'
      summary: Регистрация нового пользователя.
      tags:
      - Пользователь
swagger: "2.0"
