#!/bin/sh

commit_msg_file="$1"
commit_msg=$(cat "$commit_msg_file")
if [[ $commit_msg =~ ^\[[A-Z]+-[0-9]+\].+$ ]]; then
  exit 0
fi
echo "Ошибка: недопустимый формат сообщения. Используйте [номер задачи] сообщение."
exit 1
